<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-02-05T10:24:31Z" name="Default suite" finished-at="2020-02-05T10:25:01Z" duration-ms="30023">
    <groups>
    </groups>
    <test started-at="2020-02-05T10:24:31Z" name="Default test" finished-at="2020-02-05T10:25:01Z" duration-ms="30023">
      <class name="com.xem.qa.testcases.NewDataSourceTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.xem.qa.testcases.NewDataSourceTest@327b636c]" started-at="2020-02-05T10:24:31Z" name="setup" finished-at="2020-02-05T10:25:01Z" duration-ms="29961" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="createNewDataSource()[pri:0, instance:com.xem.qa.testcases.NewDataSourceTest@327b636c]" started-at="2020-02-05T10:25:01Z" name="createNewDataSource" finished-at="2020-02-05T10:25:01Z" duration-ms="33" status="FAIL">
          <exception class="java.lang.Error">
            <message>
              <![CDATA[Unresolved compilation problem: 
nameNew cannot be resolved to a variable
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Error: Unresolved compilation problem: 
nameNew cannot be resolved to a variable

at com.xem.qa.pages.NewDataSourcePage.CreateNewDataSourcePage(NewDataSourcePage.java:196)
at com.xem.qa.testcases.NewDataSourceTest.createNewDataSource(NewDataSourceTest.java:44)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Error -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewDataSource -->
      </class> <!-- com.xem.qa.testcases.NewDataSourceTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
